name: analog_clock
description: Analog clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  intl:
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: WeiBeiSundial
      fonts:
        - asset: assets/fonts/weibei-sundial.ttf
    - family: ZhuanSundial
      fonts:
        - asset: assets/fonts/xiaozhuan-sundial.ttf
    - family: weathericons
      fonts:
        - asset: assets/fonts/weathericons-regular-webfont.ttf
